version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=gazin
      - POSTGRES_PASSWORD=gazin
      - POSTGRES_DB=gazin
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=gazin
      - POSTGRES_PASSWORD=gazin
      - POSTGRES_DB=gazin
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    restart: always
    ports:
      - "8080:8080"
